### ISSUE TITLE
[ERROR] On disabling

### ISSUE THREAD

**Issue by MrFreasy** [JEFF-Media-GbR/Spigot-ChestSort#101]
**Used ChestSort version**
v9.0.1

**Used Spigot version**
This server is running Tuinity version git-Tuinity-"f8c0db4" (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)

**Describe the bug**
https://pastebin.com/WVsyK1J0

**Comment by mfnalex** [comment]
Sorry for the late reply. I never saw that error before, maybe Tuinity handles Permissions differently? I will check it out, thanks for the report.

**Comment by mfnalex** [comment]
Doesn't happen for me. Can you tell me on how to reproduce it?

**Comment by mfnalex** [comment]
No reply
