### ISSUE TITLE
Possible Item-Duplication when using ChestSort along with Shulker-Backpacks from CMI

### ISSUE THREAD

**Issue by J0schlZ** [JEFF-Media-GbR/Spigot-ChestSort#105]
I got a duplication-issue when i use ChestSort along with Shulker-Backpacks from CMI

Steps do reproduce:
You have 2 shulker-boxes in your inventory, (box-A, box-B)
Put box (B) into hotbar, slot 1
Put box (A) into hotbar, slot 2
Put some stuff to duplicate (e.g. diamons) into box (A)
Open box (A) with SHIFT+Rightclick from your Inventory (CMI-Backpacks-Feature)
Double-click an empty slot in your hotbar (bottom-bar of inventory-gui)
The content of box (A) is copied into box (B)

https://github.com/Zrips/CMI/issues/5112

**Comment by mfnalex** [comment]
Closing, CMI author doesn't want to fix it according to the mentioned issue -> https://github.com/Zrips/CMI/issues/5112
