### ISSUE TITLE
Can't sort in Slimefun backpacks 

### ISSUE THREAD

**Issue by isaacmarcus** [JEFF-Media-GbR/Spigot-ChestSort#108]
## Environment
Chestsort v9.5.1
Paper git-Paper-583 (MC: 1.16.5)
Slimefun DEV - 871 (git e1f0e0cd)
Metrics-Module #21
Java 8

## Describe the bug
Chestsort functions can't be used in Slimefun backpacks

## To Reproduce
open a slimefun backpack and try to use functions

## Expected behavior
Expect slimefun backpacks to function the same as chests

**Comment by mfnalex** [comment]
Hi, please enable ChestSort debug mode, do `/sort reload` and then try to use one of the hotkeys you have enabled in the backpack. Then send the console output please.

**Comment by isaacmarcus** [comment]
Did three hotkeys, first is a middle click in the backpack to auto sort, 
second is a left click outside inventory to fill backpack
thirs is a right click outside invent to empty backpack

https://pastebin.com/zKrCRJe9

**Comment by mfnalex** [comment]
That plugin is using "null" as InventoryHolder, ChestSort cannot detect it. You would have to ask the Slimefun author to either implement the ChestSort API or to use a custom inventory holder class. I cannot do anything otherwise I fear.

**Comment by mfnalex** [comment]
Has to be fixed by other plugin

**Comment by StarWishsama** [comment]
> That plugin is using "null" as InventoryHolder, ChestSort cannot detect it. You would have to ask the Slimefun author to either implement the ChestSort API or to use a custom inventory holder class. I cannot do anything otherwise I fear.

Hi, i'm maintaining a version of slimefun which used custom inventory holder for identify slimefun inventory, could you provide more details about chestsort detect mechanism?
