### ISSUE TITLE
Request Support PlaceholderAPI or API-Improvement

### ISSUE THREAD

**Issue by GeertBraakman** [JEFF-Media-GbR/Spigot-ChestSort#11]
### Issue
Hello, I would like to request a feature for your plugin, I'm creating a settings menu for my server and I would like to add an option in there to toggle chestsorting, but I can't check if the player has ChestSorting enabled or not, I can do that by a placeholder with the PlaceholderAPI, but your plugin doesn't support it. So i tried to make my own placeholder but i got the problem that the methode i need to use is package private in your plugin. 

### Solution
So my question was, can you add support for the [PlaceholderAPI](https://github.com/PlaceholderAPI/PlaceholderAPI) or just make the methode [`sortingEnabled(Player p)`](https://github.com/JEFF-Media-GbR/Spigot-ChestSort/blob/8ec32c8df5483f811db7c691db9f3b2160b1880b/src/main/java/de/jeffclan/JeffChestSort/JeffChestSortPlugin.java#L211)  public so I can acces it with the API for your plugin. 

__thank you in advance,__
Geert Braakman
Administator/Developer on [LuminexMC](https://www.luminexmc.com/)

**Comment by mfnalex** [comment]
Of course, that's a great suggestion. This will be added shortly. Thanks

**Comment by mfnalex** [comment]
The method is now public and documented here: https://github.com/JEFF-Media-GbR/Spigot-ChestSort/blob/master/HOW_TO_USE_API.md

**Comment by mfnalex** [comment]
I hope this change suits your needs. I have never used PlaceholderAPI so if you could create a pull request for adding placeholders, that would be awesome.

**Comment by mfnalex** [comment]
I am interested in seeing ChestSort with your GUI. Can I join your server sometime and try it? :)
