### ISSUE TITLE
Losing items from inventory

### ISSUE THREAD

**Issue by Bloodlex** [JEFF-Media-GbR/Spigot-ChestSort#111]
**Used ChestSort version**
9.7.1

**Used Spigot version**
Paper version git-Paper-581 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)

**Describe the bug**
My players are losing items in inventory 🙁 . I don't know if it is caused by this plugin, but I also can't exclude this possibility. Could you please tell me, if that may happen with your plugin?

**To Reproduce**
Hard to tell, but after last update (9.7.1) my players are reporting a lot of cases when items disappear from the inventory and they are convinced that the items must have been lost due to some error.

**Expected behavior**
Items should never disappear from the inventory

**Additional context**
Here is the list of my other plugins:

Plugins (67): ActionHealth*, AdvancedLogger*, AdvancedRegionMarket, ArmShopBridge, AsyncWorldEdit, AuthMe, BetterBees, BetterHeads, CommandBlocks, CommandNotifier, CommandPanels, ContainerPassthrough, CraftBook, DeathPenalties, dynmap*, Dynmap-WorldGuard*, EasyCarts, Epidemic, Essentials, EssentialsChat, GoldenEnchants, GSit, Harbor, HolographicDisplays, Images, InteractiveBooks, JetsAntiAFKPro, Jobs, KeepChunks, LangUtils, Lasso, LastLoginAPI, LeaderHeadsRevamped, LogBlock, LuckPerms, LWC, MobArena, MyCommand, NBTAPI, NexEngine, NoElytra*, OpenInv, OreAnnouncer, Orebfuscator, PetMaster, Pingas*, PL-Hide-Pro, PlaceholderAPI, Plan, PortalFix*, ProtocolLib, PvPManager, QuickShop, QuickShopDynmap, RegionRaid, SAML, SkinsRestorer, Spartan, SuperVanish, TAB, TitleManager, TreeAssist, Vault, VillagerOptimiser, WorldEdit, WorldGuard, WorldGuardExtraFlags

If you have any hints on that, how can I further investigate the problem, I'd be more than happy to do that. Thank you very much! Your plugin is great and I'd really like to have it back when I'm sure that it's not the cause 🙁

**Comment by mfnalex** [comment]
Hi, do you have any more information on "when" they lose their items? You could try to remove the "chestsort.use" permission from your players (so they cannot use ChestSort anymore) and see if they still report item loss. If yes, it is DEFINITELY not a ChestSort problem. If no, we have to investigate if there is an interference between ChestSort and another plugin, and then we will try to figure out what the other plugin is and why it happens :)

**Comment by mfnalex** [comment]
No reply for over a month -> closed.
