### ISSUE TITLE
New Translation Chinese (Traditional) 繁體中文

### ISSUE THREAD

**Issue by gregman98** [JEFF-Media-GbR/Spigot-ChestSort#115]
Language
Chinese (Traditional) 繁體中文

Translation
message-when-using-chest: "&7小提醒 ： 輸入 &6/chestsort&7 來開啟自動整理儲物箱。"
message-when-using-chest2: "&7小提醒 ： 輸入 &6/chestsort&7 來關閉自動整理儲物箱。"
message-sorting-disabled: "&c已關閉&7自動整理儲物箱。"
message-sorting-enabled: "&a已開啟&7自動整理儲物箱。"
message-inv-sorting-disabled: "&c已關閉&7自動整理物品欄。"
message-inv-sorting-enabled: "&a已開啟&7自動整理物品欄。"
message-player-inventory-sorted: "&7已成功整理物品欄。"
message-error-players-only: "&c錯誤 ： 這個指令只能由玩家使用。"
message-error-invalid-options: "&c錯誤 ： 未知的選項 %s，有效的選項為 %s。"
message-hotbar-container-sorted: "&a已成功整理儲物箱 ！"
message-gui-enabled: "&a開啟"
message-gui-disabled: "&c關閉"
message-gui-middle-click: "點擊中鍵"
message-gui-shift-click: "Shift + 點擊左鍵"
message-gui-double-click: "雙點擊左鍵"
message-gui-shift-right-click: "Shift + 點擊右鍵"
message-gui-left-click: "填滿儲物箱 （點擊左鍵/雙點擊左鍵）"
message-gui-right-click: "清空儲物箱 （點擊右鍵/雙點擊右鍵）"
message-gui-left-click-outside: "對儲物箱點擊左鍵"

I'm Flandre_tw. From a translation team. Hope to be approved.

**Comment by Cazcez** [comment]
Thanks for translation, but what's the difference between your translation and #114?

**Comment by gregman98** [comment]
Change #114's punctuation to Chinese Traditional format.

**Comment by mfnalex** [comment]
Thx, will be added in the next update

**Comment by mfnalex** [comment]
Added in 10.1.0
