### ISSUE TITLE
1.17 keybinds problem

### ISSUE THREAD

**Issue by CNoise** [JEFF-Media-GbR/Spigot-ChestSort#116]
**Used ChestSort version**
v10.0.4

**Used Spigot version**
CraftBukkit version 3141-Spigot-66f9d3c-72a2901 (MC: 1.17) (Implementing API version 1.17-R0.1-SNAPSHOT)

**Describe the bug**
While I have all the sorting keybinds except middle-click disabled in my config file, I still can use all the keybinds to sort inventory and containers. At the same time I have additional keybinds (double click outside of inventory to put / take items) enabled in the config, but those don't work in game.
Config file: https://pastebin.com/98Ls9CpQ

**Additional context**
Plugins (12): Brewery, AnvilColor, RotationWrench, SkinsRestorer, WorldEdit, LightPerms, DeathCoordinates, DisplayName, Essentials, ArbitraryPortals, EssentialsChat, ChestSort
At the server startup I can see the correct settings: https://pastebin.com/Zjuj4Ug0

**Comment by CNoise** [comment]
Not sure if these would be of any use, but I enabled both debugs in config and collected some output.
Double left click to sort chest while double click is disabled: https://pastebin.com/wfjaGYLe
Double right click outside of inventory to take items which it is enabled: https://pastebin.com/hLrzsL8n

**Comment by mfnalex** [comment]
/sort hotkeys

The config, as it says, only sets the values for new players.
