### ISSUE TITLE
Problem with Modded Server

### ISSUE THREAD

**Issue by huyhhuy1410** [JEFF-Media-GbR/Spigot-ChestSort#121]
So i'm using the lastest version of ChestSort plugin with a mod called Pandoras Creatures.
This mod added some new containers called "End Troll Box" (a upgrade from Shulker Box). And I couldn't sort those ones.
So it's not worked with custom containers?
Could you fix that?
Many thanks !

**Comment by mfnalex** [comment]
Hi, the Spigot API cannot access custom Forge items. It's simply not possible for Spigot to "see" those items, sorry.
