### ISSUE TITLE
Error In Console

### ISSUE THREAD

**Issue by LucidusMC** [JEFF-Media-GbR/Spigot-ChestSort#13]
**Used version**
Tell us your Spigot/Minecraft version and ChestSort version
Paper 1.13.2 (624)
CheetSort 3.7

**Describe the bug**
Error in console while accessing inventory (best guess)

https://pastebin.com/G9YhnEGk

**To Reproduce**
How can the behaviour be reproduced?

Not sure.

**Expected behavior**

**Additional context**
Only happens in this version, previous ones did not.

Thanks!

**Comment by eot13** [comment]
By closing an inventory that doesn't belong to a block, i've the same

**Comment by mfnalex** [comment]
Can you explain? How do you produce this error in detail?

**Comment by mfnalex** [comment]
Please try again with the latest version and let me know if this fixes it
