### ISSUE TITLE
Automatic Refill

### ISSUE THREAD

**Issue by FatalBlade** [JEFF-Media-GbR/Spigot-ChestSort#32]
**Is your feature request related to a problem? Please describe.**
Nope

**Additional context**
Would it be possible to implement the ability to automatically refill your hotbar once you run out of a stack of items?

**Comment by mfnalex** [comment]
Yes, that will definitely be possible. It is already on my todo list. I will leave this issue open as a reminder for myself :)

**Comment by dioleev** [comment]
This, but for tools. And automatically select best tool for block type maybe?

**Comment by mfnalex** [comment]
Sorry for the long waiting time. Still on the to do list though.

**Comment by mfnalex** [comment]
> This, but for tools. And automatically select best tool for block type maybe?

I made this as a separate plugin called BestTools. It also includes refilling the hotbar.
