### ISSUE TITLE
Automatically use best tool to interact with blocks that affect durability

### ISSUE THREAD

**Issue by dioleev** [JEFF-Media-GbR/Spigot-ChestSort#35]
Automatic tool selection makes interacting with blocks fast and effortless, mining feels more fluid.

**Describe the solution you'd like**
ChestSort automatically chooses correct tools when interacting with blocks that affect durability:
- Pickaxe to mine stones, ores, furnaces etc.
- Axe to chop wood, fences, craftbench etc.
After actions is complete ChestSort switches back to the slot that was selected before automatic switching. If the best tool is not possible, then ChestSort uses something that won't lose durability:

- I attempt to dig dirt with no shovel while holding a Pickaxe. ChestSort switches to empty hand, a Torch, Shield etc.

**Comment by mfnalex** [comment]
Hi, that is an interesting idea, I will think about adding it.

**Comment by mfnalex** [comment]
This will probably not be an addition to ChestSort, but rather a separate plugin. I will leave this issue open as a reminder to myself and others.

**Comment by mfnalex** [comment]
See my plugin BestTools on Spigot.
