### ISSUE TITLE
Change Hotkey Middle click to mouse extra key?

### ISSUE THREAD

**Issue by IanWPG** [JEFF-Media-GbR/Spigot-ChestSort#39]
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
I would like to press Mouse Button 4 or 5 to sort any slot, is that possible? Kinda hard to sort a chest if all inventory slots are full to be able to shift click. Seems middle mouse button does not work for whatever reason.

**Describe alternatives you've considered**
Autohotkey 3rd party program, annoying if you forget to turn it off.

**Additional context**
N/A

**Comment by IanWPG** [comment]
Update, discovered if you rebind block picker to another key were previously it was Middle click the middle click for chest sort does not work.

**Comment by mfnalex** [comment]
There is nothing I can do here without client mods. Please have a look at the Spigot API regarding ClickTypes: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/event/inventory/ClickType.html
Other clicks cannot be recognized by the server.
