### ISSUE TITLE
1.14 Error

### ISSUE THREAD

**Issue by juanluna96** [JEFF-Media-GbR/Spigot-ChestSort#40]
**Used ChestSort version**
Version 7.1

**Describe the bug**
Hi, i tried to install the mod in Minecraft 1.14 with forge 28.0.45 but I get the following message
![01](https://user-images.githubusercontent.com/28470975/63036334-776a6c80-be82-11e9-8269-3a91af47639f.png)

**Expected behavior**
Maybe i didn't install it well or it is not compatible with the forge version?

**Comment by mfnalex** [comment]
Sorry, ChestSort is a Spigot/Bukkit plugin, not a Forge mod.
