### ISSUE TITLE
translate french

### ISSUE THREAD

**Issue by demon57730** [JEFF-Media-GbR/Spigot-ChestSort#41]
translate french

message-when-using-chest: "&7Astuce: Écris &6/chestsort&7 pour activer le classement automatique."
message-when-using-chest2: "&7Astuce: Écris &6/chestsort&7 pour désactiver le classement automatique."
message-sorting-disabled: "&7Le classement automatique a été &cdésactivé&7."
message-sorting-enabled: "&7Le classement automatique a été &aactivé&7."
message-player-inventory-sorted: "&7Votre inventaire a été trié."
message-error-players-only: "&cErreur: Cette commande ne peut être utilisée que par des joueurs."
message-error-invalid-options: "&cErreur: option inconnue %s. Les options valides sont %s."
message-gui-enabled: "&aActivé"
message-gui-disabled: "&cDésactivé"
message-gui-middle-click: "Clic du milieu"
message-gui-shift-click: "Shift + Click"
message-gui-double-click: "Double-Click"
message-gui-shift-right-click: "Shift + Right-Click"

**Comment by mfnalex** [comment]
Thanks; will be added with the next update
