### ISSUE TITLE
Potions sorting not supported

### ISSUE THREAD

**Issue by andris155** [JEFF-Media-GbR/Spigot-ChestSort#42]
**Used ChestSort version**
Tell us your ChestSort version
ChestSort version 7.1

**Used Spigot version**
Tell us your Spigot version (output of /version). Please also tell us if you use another fork like Paper, etc.
This server is running Paper version git-Paper-177 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)

**Describe the bug**
Potions sorting not supported

**To Reproduce**
How can the behaviour be reproduced?
Sort different potions.

**Expected behavior**
Sort portions

**Additional context**

**Comment by mfnalex** [comment]
How exactly are potions not sorted?

**Comment by andris155** [comment]
The plugin does not sort by potion type.

**Comment by andris155** [comment]
<img width="263" alt="Annotation 2019-09-04 190557" src="https://user-images.githubusercontent.com/8324198/64275958-0bda6300-cf47-11e9-9997-8bc24bf371de.png">

**Comment by mfnalex** [comment]
Thanks, I will keep this issue in mind for the next version. Sorry for the delayed answer

**Comment by mfnalex** [comment]
Andris155, do you have discord? There is one problem we have to solve for the potion sorting and it would be nice if we could for a few minutes

**Comment by andris155** [comment]
I prefer written communication, but I have discord.

**Comment by mfnalex** [comment]
I haven't used potions since ages. Can a potion only ever have one effect, or are there also potions with several different effects?

**Comment by andris155** [comment]
Most of them have one kind of effect, but there are some that have more.

**Comment by mfnalex** [comment]
I will work on this today, thanks again for the idea.

**Comment by mfnalex** [comment]
Has been added as of 7.3, thanks.
