### ISSUE TITLE
HotKeys perms not working

### ISSUE THREAD

**Issue by joguerreiro** [JEFF-Media-GbR/Spigot-ChestSort#43]
**Used ChestSort version**
7.1

**Used Paper version**
git paper 207

**Describe the bug**
we cant disabled some of the hotkeys

**To Reproduce**

> #########################
#########################
#
#   www.jeff-media.de
#

#
# This config file will be updated automatically with every new release of ChestSort.
# Don't worry! Your changes will be kept after every update.
#

#
# Please note that players will need the chestsort.use permission
# or have to be OP to be able to use automatic chest sorting.
# To use /invsort, the permission chestsort.use.inventory is required.
#

# when set to false, new players will have to run /chestsort
# once to enable automatic chest sorting.
sorting-enabled-by-default: false

# when set to true, players with sorting DISABLED will be
# shown a message on how to enable automatic chest sorting
# when they use a chest for the first time.
# consider setting this to true when you disable sorting by default.
# see also -> message-when-using-chest
show-message-when-using-chest: true

# when set to true, players with sorting ENABLED will be
# shown a message on how to disable automatic chest sorting
# when they use a chest for the first time.
# consider setting this to true when you enable sorting by default.
# see also -> message-when-using-chest2
show-message-when-using-chest-and-sorting-is-enabled: false

# when set to true, the messages are shown again when a player
# logs out and back in and then uses a chest again.
show-message-again-after-logout: true

# to sort by category, we need category files. ChestSort comes
# with a number of pregenerated category files, named
# 900-valuables.txt, 910-tools.txt, 920-combat.txt, ...
# If you wish to edit those, you can disable the generation of these
# files, because otherwise all your changes in the pregenerated
# files will be overwritten on each server startup.
# However, a much smarter option is to copy the default files
# and rename them to from 900... to 800... and edit those instead.
auto-generate-category-files: true

# you can choose when ChestSort should sort chests.
# The default option is to sort when an inventory is closed.
# This is useful, because the onInventoryClose event never gets fired
# when access to the chest is forbidden by another plugin, e.g. WorldGuard
# You can also sort whenenver a chest is opened. ChestSort will then check
# if the onInventoryOpenEvent gets cancelled. If it does get cancelled,
# ChestSort will not sort the chest. However, if a plugin uses the
# MONITOR event priority, ChestSort cannot detect this.
# If you have problems with unaccessible chests being sorted, set this
# option to "close". If you want, you can sort twice, however this is not
# very useful.
# If you don't know what to put here, just use the default "close"
# Available options: open, close, both
sort-time: close

# should we check for updates?
# when enabled, a message is printed in the console if a new
# version has been found, and OPs will be notified when they join the server
# When set to true, we will check for updates on startup and every 24 hours
# When set to on-startup, we will only check on startup
# When set to false, don't check for updates
check-for-updates: true

# when set to true, show some verbose information on startup
verbose: true

#########################
#########################

# Instead of automatic sorting, you can also use hotkeys (see below)
# when using an inventory to have it sorted immediately.
# You can disable this by setting this to false.
allow-hotkeys: true

# You can disable/enable certain hotkeys when you have allow-hotkeys enabled.
# Hotkeys that could interfere with Minecraft's normal behaviour (e.g.
# shift+left-click) only work on empty slots, so don't worry about them.
# Players can also enable/disable all shortcuts individually via /chestsort hotkeys
hotkeys:
  # Use middle click (mousewheel) on ANY inventory slot as hotkey
  middle-click: true 
  # Use shift + left-click on any EMPTY inventory slot as hotkey
  shift-click: true
  # Use double left-click on any EMPTY inventory slot as hotkey
  double-click: false 
  # Use shift + right-click on any EMPTY inventory slot as hotkey
  shift-right-click: true
  
#########################
#########################

# You can disable ChestSort for certain worlds. Each world's name has to
# be on a separate line, starting with a hyphen and followed by a space.
# You can also use the YAML array notation: [world1, world2, world3]

# Example:
#
# disabled-worlds:
# - world_nether
# - world_the_end

disabled-worlds:

##########################
##########################

# ChestSort can hook into other plugins to allow better sorting
# for items belonging to 3rd party plugins.
# You do NOT have to disable the hooks for plugins you don't have
# installed. ChestSort will automatically check if the plugins
# are installed.

##### CrackShot #####
# When CrackShot is installed, all CrackShot weapons will be
# grouped together and sorted by their name
hook-crackshot: true
# You can define a custom name that will be used as prefix
# for all CrackShot weapon names.
# E.g. when you set this to "crackshot_weapon", an AK-47
# will be called "crackshot_weapon_AK-47"
hook-crackshot-prefix: "crackshot_weapon"

##### InventoryPages #####
# When InventoryPages is installed, ChestSort will not sort
# the "Next Page" and "Prev Page" buttons. You should not
# disable this behaviour unless you know what you are doing!
hook-inventorypages: true

##########################
##########################

# Advanced: how to sort things! See below for examples.
# Only change this if you know what you are doing.
#
# Available variables:
# {category}          order stuff by category as defined in plugins/ChestSort/categories/<category>.txt
# {keepCategoryOrder} orders stuff in the same category according to their line numbers in the category file
# {itemsFirst}        put items before blocks
# {blocksFirst}       put blocks before items
# {name}              returns the name (e.g. DIRT, GRASS_BLOCK, BIRCH_LOG, DIAMOND_SWORD, ...)
# {color}             returns the color, e.g. light_blue for wool. Empty if block/item is not dyeable
# {customName}        returns the display name if set (e.g. with an anvil)
# {lore}              returns the lore if set
#
# Warning: You must not use spaces and fields have to be separated by commas.
#
# Examples:
#   sort by name and color:
#     '{name},{color}'
#
#   sort by name and color, but put items before blocks:
#     '{itemsFirst},{name},{color}'
#
#   sort by name and color, but put blocks before items:
#     '{blocksFirst},{name},{color}'
#
#   sort by category, then put items before blocks and sort by name and color
#      '{category},{itemsFirst},{name},{color}'
#
#   sort by category, but keep exactly the same order as defined in each category file, then sort any undefined items by name and color
#      '{category},{keepCategoryOrder},{name},{color}
#
sorting-method: '{category},{itemsFirst},{name},{color}'

#########################
#########################

# Available color codes:
# &0 Black        &6 Gold       &c Red
# &1 Dark Blue    &7 Gray       &d Light Purple
# &2 Dark Green   &8 Dark Gray  &e Yellow
# &3 Dark Aqua    &9 Blue       &f White
# &4 Dark Red     &a Green
# &5 Dark Purple  &b Aqua

# Available formatting codes:
# &k Obfuscated   &m Strikethrough
# &l Bold         &o Italic
# &n Underline    &r Reset

# IMPORTANT NOTE:
# Some messages contain placeholders (%s). You must not remove those, or you will get exceptions in the console

##### You can edit these messages yourself or uncomment the existing translations (see below)
message-when-using-chest: "&7Hint: Type &6/chestsort&7 to enable automatic chest sorting."
message-when-using-chest2: "&7Hint: Type &6/chestsort&7 to disable automatic chest sorting."
message-sorting-disabled: "&7Automatic chest sorting has been &cdisabled&7."
message-sorting-enabled: "&7Automatic chest sorting has been &aenabled&7."
message-player-inventory-sorted: "&7Your inventory has been sorted."
message-error-players-only: "&cError: This command can only be run by players."
message-error-invalid-options: "&cError: Unknown option %s. Valid options are %s."
message-gui-enabled: "&aEnabled"
message-gui-disabled: "&cDisabled"
message-gui-middle-click: "Middle-Click"
message-gui-shift-click: "Shift + Click"
message-gui-double-click: "Double-Click"
message-gui-shift-right-click: "Shift + Right-Click"

##### English
#message-when-using-chest: "&7Hint: Type &6/chestsort&7 to enable automatic chest sorting."
#message-when-using-chest2: "&7Hint: Type &6/chestsort&7 to disable automatic chest sorting."
#message-sorting-disabled: "&7Automatic chest sorting has been &cdisabled&7."
#message-sorting-enabled: "&7Automatic chest sorting has been &aenabled&7."
#message-player-inventory-sorted: "&7Your inventory has been sorted."
#message-error-players-only: "&cError: This command can only be run by players."
#message-error-invalid-options: "&cError: Unknown option %s. Valid options are %s."
#message-gui-enabled: "&aEnabled"
#message-gui-disabled: "&cDisabled"
#message-gui-middle-click: "Middle-Click"
#message-gui-shift-click: "Shift + Click"
#message-gui-double-click: "Double-Click"
#message-gui-shift-right-click: "Shift + Right-Click"

##### Note: Some messages are still untranslated. Please send me your translation at SpigotMC
#message-when-using-chest: "&7提示: 输入 &6/chestsort&7 来启用自动整理箱子."
#message-when-using-chest2: "&7提示: 输入 &6/chestsort&7 来关闭自动整理箱子."
#message-sorting-disabled: "&7自动整理箱子已 &c关闭&7."
#message-sorting-enabled: "&7自动整理箱子已 &a启用&7."
#message-player-inventory-sorted: "&7已成功整理你的背包."
#message-error-players-only: "&c错误: 指令只能由玩家运行."
#message-error-invalid-options: "&c错误: 位置选项 %s. 有效选项为 %s."
#message-gui-enabled: "&aEnabled"
#message-gui-disabled: "&cDisabled"
#message-gui-middle-click: "Middle-Click"
#message-gui-shift-click: "Shift + Click"
#message-gui-double-click: "Double-Click"
#message-gui-shift-right-click: "Shift + Right-Click"

##### Note: Some messages are still untranslated. Please send me your translation at SpigotMC
#message-when-using-chest: "&7小提醒: 輸入 &6/chestsort&7 來開啟自動整理箱子"
#message-when-using-chest2: "&7小提醒: 輸入 &6/chestsort&7 來關閉自動整理箱子"
#message-sorting-disabled: "&7自動整理箱子已 &c關閉&7"
#message-sorting-enabled: "&7自動整理箱子已 &a開啟&7"
#message-player-inventory-sorted: "&7你的背包已成功整理."
#message-error-players-only: "&c錯誤: 這個指令只能由玩家使用"
#message-error-invalid-options: "&c錯誤: 未知選項 %s. 有效的選項為 %s."
#message-gui-enabled: "&aEnabled"
#message-gui-disabled: "&cDisabled"
#message-gui-middle-click: "Middle-Click"
#message-gui-shift-click: "Shift + Click"
#message-gui-double-click: "Double-Click"
#message-gui-shift-right-click: "Shift + Right-Click"

##### Note: Some messages are still untranslated. Please send me your translation at SpigotMC
#message-when-using-chest: "&7Hint: Gebruik &6/chestsort&7 om automatische kist sortering aan te zetten."
#message-when-using-chest2: "&7Hint: Gebruik &6/chestsort&7 om automatische kist sortering uit te zetten."
#message-sorting-disabled: "&7Automatische kist sortering is &cuitgeschakeld&7."
#message-sorting-enabled: "&7Automatische kist sortering is &aingeschakeld&7."
#message-player-inventory-sorted: "&7Je inventaris is gesorteerd."
#message-error-players-only: "&cFout: Dit commando kan alleen door spelers worden gebruikt."
#message-error-invalid-options: "&cFout: Onbekende optie %s. Mogelijke opties zijn %s."
#message-gui-enabled: "&aEnabled"
#message-gui-disabled: "&cDisabled"
#message-gui-middle-click: "Middle-Click"
#message-gui-shift-click: "Shift + Click"
#message-gui-double-click: "Double-Click"
#message-gui-shift-right-click: "Shift + Right-Click"

##### Note: Some messages are still untranslated. Please send me your translation at SpigotMC
#message-when-using-chest: "&7Astuce: Écris &6/chestsort&7 pour activer le classement automatique."
#message-when-using-chest2: "&7Astuce: Écris &6/chestsort&7 pour désactiver le classement automatique."
#message-sorting-disabled: "&7Le classement automatique a été &cdésactivé&7."
#message-sorting-enabled: "&7Le classement automatique a été &aactivé&7."
#message-player-inventory-sorted: "&7Your inventory has been sorted."
#message-error-players-only: "&cErreur: Cette commande ne peut être utilisée que par des joueurs."
#message-error-invalid-options: "&cError: Unknown option %s. Valid options are %s."
#message-gui-enabled: "&aEnabled"
#message-gui-disabled: "&cDisabled"
#message-gui-middle-click: "Middle-Click"
#message-gui-shift-click: "Shift + Click"
#message-gui-double-click: "Double-Click"
#message-gui-shift-right-click: "Shift + Right-Click"

##### German
#message-when-using-chest: "&7Hinweis: Benutze &6/chestsort&7 um die automatische Kistensortierung zu aktivieren."
#message-when-using-chest2: "&7Hinweis: Benutze &6/chestsort&7 um die automatische Kistensortierung zu deaktivieren."
#message-sorting-disabled: "&7Automatische Kistensortierung &cdeaktiviert&7."
#message-sorting-enabled: "&7Automatische Kistensortierung &aaktiviert&7."
#message-player-inventory-sorted: "&7Dein Inventar wurde sortiert."
#message-error-players-only: "&cFehler: Dieser Befehl ist nur für Spieler verfügbar."
#message-error-invalid-options: "&cFehler: Unbekannte Option %s. Gültige Optionen sind %s."
#message-gui-enabled: "&aAktiviert"
#message-gui-disabled: "&cDeaktiviert"
#message-gui-middle-click: "Mittel-Klick"
#message-gui-shift-click: "Shift + Klick"
#message-gui-double-click: "Doppelklick"
#message-gui-shift-right-click: "Shift + Rechtsklick"

##### Note: Some messages are still untranslated. Please send me your translation at SpigotMC
#message-when-using-chest: "&7Nota: inserire &6/chestsort&7 per abilitare l'ordinamento automatico dei bauli."
#message-when-using-chest2: "&7Nota: inserire &6/chestsort&7 per disabilitare l'ordinamento automatico dei bauli."
#message-sorting-disabled: "&7L'ordinamento automatico dei bauli è stato &cdisattivato&7."
#message-sorting-enabled: "&7L'ordinamento automatico dei bauli è stato &aattivato&7."
#message-player-inventory-sorted: "&7Il tuo inventario è stato ordinato."
#message-error-players-only: "&cErrore: questo comando è disponibile solo per i giocatori."
#message-error-invalid-options: "&cErrore: Parametro sconosciuto %s. I parametri validi sono %s."
#message-gui-enabled: "&aEnabled"
#message-gui-disabled: "&cDisabled"
#message-gui-middle-click: "Middle-Click"
#message-gui-shift-click: "Shift + Click"
#message-gui-double-click: "Double-Click"
#message-gui-shift-right-click: "Shift + Right-Click"

##### Note: Some messages are still untranslated. Please send me your translation at SpigotMC
#message-when-using-chest: "&7ヒント: &6/chestsort&7 と入力して自動チェスト整理を有効にできます。"
#message-when-using-chest2: "&7ヒント: &6/chestsort&7 と入力すると自動チェスト整理を無効にできます。"
#message-sorting-disabled: "&7自動チェスト整理は現在 &cOFF&7です。"
#message-sorting-enabled: "&7自動チェスト整理は現在 &aON&7です。"
#message-error-players-only: "&cエラー: このコマンドはプレイヤーのみ実行できます。"
#message-player-inventory-sorted: "&7Your inventory has been sorted."
#message-error-invalid-options: "&cError: Unknown option %s. Valid options are %s."
#message-gui-enabled: "&aEnabled"
#message-gui-disabled: "&cDisabled"
#message-gui-middle-click: "Middle-Click"
#message-gui-shift-click: "Shift + Click"
#message-gui-double-click: "Double-Click"
#message-gui-shift-right-click: "Shift + Right-Click"

##### Note: Some messages are still untranslated. Please send me your translation at SpigotMC
#message-when-using-chest: "&7Dica: Digite &6/chestsort&7 para habilitar a organização automática."
#message-when-using-chest2: "&7Dica: Digite &6/chestsort&7 para desabilitar a organização automática."
#message-sorting-disabled: "&7A Organização automática de baús foi &cdesabilitada&7."
#message-sorting-enabled: "&7A Organização automática de baús foi &ahabilitada&7."
#message-player-inventory-sorted: "&7Seu inventário foi organizado."
#message-error-players-only: "&cErro: Esse comando não pode ser executado por jogadores."
#message-error-invalid-options: "&cError: Unknown option %s. Valid options are %s."
#message-gui-enabled: "&aEnabled"
#message-gui-disabled: "&cDisabled"
#message-gui-middle-click: "Middle-Click"
#message-gui-shift-click: "Shift + Click"
#message-gui-double-click: "Double-Click"
#message-gui-shift-right-click: "Shift + Right-Click"

##### Note: Some messages are still untranslated. Please send me your translation at SpigotMC
#message-when-using-chest: "&7Подсказка: введите &6/chestsort&7, чтобы включить автоматическую сортировку вещей в сундуках."
#message-when-using-chest2: "&7Подсказка: введите &6/chestsort&7, чтобы отключить автоматическую сортировку вещей в сундуках."
#message-sorting-disabled: "&7Автоматическая сортировка вещей в сундуках была &cотключена&7."
#message-sorting-enabled: "&7Автоматическая сортировка вещей в сундуках была &aвключена&7."
#message-player-inventory-sorted: "&7Ваш инвентарь был отсортирован."
#message-error-players-only: "&cОшибка: эта команда может быть использована только игроками."
#message-error-invalid-options: "&cОшибка: Неизвестная опция %s. Допустимые опции: %s."
#message-gui-enabled: "&aEnabled"
#message-gui-disabled: "&cDisabled"
#message-gui-middle-click: "Middle-Click"
#message-gui-shift-click: "Shift + Click"
#message-gui-double-click: "Double-Click"
#message-gui-shift-right-click: "Shift + Right-Click"

##### Note: Some messages are still untranslated. Please send me your translation at SpigotMC
#message-when-using-chest: "&7Pista: Usa &6/chestsort&7 para activar el orden automático de los cofres."
#message-when-using-chest2: "&7Pista: Usa &6/chestsort&7 para desactivar el orden automático de los cofres."
#message-sorting-disabled: "&7Orden automático de los cofres &cdesactivado&7."
#message-sorting-enabled: "&7Orden automático de los cofres &aactivado&7."
#message-player-inventory-sorted: "&7Tu inventario ha sido ordenado."
#message-error-players-only: "&cError: Este comando solo puede ser ejecutado por jugadores."
#message-error-invalid-options: "&cError: %s es una opción inválida. Las opciones válidas son: %s."
#message-gui-enabled: "&aEnabled"
#message-gui-disabled: "&cDisabled"
#message-gui-middle-click: "Middle-Click"
#message-gui-shift-click: "Shift + Click"
#message-gui-double-click: "Double-Click"
#message-gui-shift-right-click: "Shift + Right-Click"

##### Note: Some messages are still untranslated. Please send me your translation at SpigotMC
#message-when-using-chest: "&7Ipucu: &6/chestsort&7 Yazarak Otomatik Sandık Organizasyon Sistemini Aktif Edebilirsin."
#message-when-using-chest2: "&7Ipucu: &6/chestsort&7 Yazarak Otomatik Sandık Organizasyon Sistemini Kapatabilirsin."
#message-sorting-disabled: "&7Otomatik Sandık Organizasyonu &cKapatıldı&7."
#message-sorting-enabled: "&7Otomatik Sandık Organizasyonu &aAçıldı&7."
#message-player-inventory-sorted: "&7Envanteriniz Düzenlendi."
#message-error-players-only: "&cHata: Bu Komut Yalnızca Oyuncular Tarafından Kullanılabilir."
#message-error-invalid-options: "&cHata: Bilinmeyen Ayar %s."
#message-gui-enabled: "&aEnabled"
#message-gui-disabled: "&cDisabled"
#message-gui-middle-click: "Middle-Click"
#message-gui-shift-click: "Shift + Click"
#message-gui-double-click: "Double-Click"
#message-gui-shift-right-click: "Shift + Right-Click"

#########################
#########################

# please do not change the following line manually!
config-version: 19

**Expected behavior**
so we can disable and enabled some of the hotkeys via the config 

**Additional context**

**Comment by mfnalex** [comment]
First of all: sorry for the late reply! Please note that disabled shortcuts will only have an effect for new players. Once a new player joins the server, he/she will have the shortcuts enabled that are defined in the config. Does the issue still persist?

**Comment by mfnalex** [comment]
If this problem still exists, please open a new issue.
