### ISSUE TITLE
Shulker inventories deleted/duplicated

### ISSUE THREAD

**Issue by Spoonerj1** [JEFF-Media-GbR/Spigot-ChestSort#44]
**Used ChestSort version**
ChestSort 7.1

**Used Spigot version**
Spigot 1.14.4 Jenkins build 2482

**Describe the bug**
On my server shulker boxes in the players inventory can be accessed without placing them on the ground. To do so, they shift+click the shulker box, and it opens the inventory like you would normally see it. 
In this bug, we have seen 2 shulker boxes get cleared. At another time one shulker box (lets call it s1) was duplicated over the inventory that was in a second box (call it s2), deleting the items from 
s2. 

**To Reproduce**
How can the behavior be reproduced? 
I'm still trying to determine this exactly, but I have confirmed the issue after it was reported. It seems to be a rare case, caused by sorting the inventory while moving items into the shulker box after opening it inside the inventory screen. I have tested it repeatedly for two days and only been able to reproduce it once on my own. But it definitely only happens after sorting the inventory with the shulker box inside the inventory. (it happened to me after the shulker box was moved by the sorting process) 

**Expected behavior**
I expected the shulker inventory to remain untouched. 
"Dude, where's my items?" -Ashton Kutcher probably

**Additional context**
We use CMI to allow players to open the shulker boxes. I tested without this and was able to reproduce the issue. (I tested without it because players said it happened after sorting)

**Comment by mfnalex** [comment]
Thanks for the report. You probably got some exceptions in the console, right?

Unfortunately, CMI is a paid premium plugin. I might message the developer if I can get a version for free, otherwise I will not be able to fix it.

Please have a look for console errors when the clearing/duplication appears.

**Comment by Spoonerj1** [comment]
Cmi has a stripped version that is available for free for devs to use. It wont function as a plugin on a server, so Idk if that helps much for this. For what I have seen, there is no error in console

**Comment by hkj7913** [comment]
I had the same problem.
To another shulker backpacks plugin the test results show that it is not a ChestSort problem, but a CMI problem.
Another plugin I used = https://www.spigotmc.org/resources/shulker-backpacks-1-14.67466/

**Comment by mfnalex** [comment]
Please provide a link to the developer version of CMI and I will see what I can do. Also, I am very sorry for the late reply.

**Comment by mfnalex** [comment]
> I had the same problem.
> To another shulker backpacks plugin the test results show that it is not a ChestSort problem, but a CMI problem.
> Another plugin I used = https://www.spigotmc.org/resources/shulker-backpacks-1-14.67466/

The linked plugin ( https://www.spigotmc.org/resources/shulker-backpacks-1-13-1-15.67466/ ) seems to work without problems. Maybe I could even add support to sort the shulker backpacks if anyone is interested.

**Comment by mfnalex** [comment]
Since I don't have access to CMI, I cannot work on this right now. If someone is using CMI, feel free to open a pull request.
