### ISSUE TITLE
Feature Request for Standalone Hotkey Sorting

### ISSUE THREAD

**Issue by Lumivescence** [JEFF-Media-GbR/Spigot-ChestSort#45]
**Is your feature request related to a problem? Please describe.**
In our server we have decided that automatic sorting doesn't fit well with our vision for a SMP and the current automatic sorting can be unpredictable when there are 2 players using the same chest at once. Currently, for players to have access to hotkey sorting, they need to also have access to the automatic chest sorting commands.

**Describe the solution you'd like**
I would like to have a way to allow players to be able to sort using the hotkeys without also having access to automatic sorting.

**Describe alternatives you've considered**
Maybe hotkey sorting can become its own permission group instead of being tied into chestsort.use and chestsort.use.inventory

**Additional context**
N/A

**Comment by mfnalex** [comment]
Thank you, that's a good idea. ChestSort will soon be updated for the new 1.15 items, and I will include your requested feature.

**Comment by Lumivescence** [comment]
Thanks for the quick reply, looking forward to it.
