### ISSUE TITLE
Chinese translation for new versions

### ISSUE THREAD

**Issue by Aira-Sakuranomiya** [JEFF-Media-GbR/Spigot-ChestSort#46]
My Minecraft ID is Isla_SakuraNMY and this is my new translation into Chinese for new versions.
ヾ(•ω•`)o

message-when-using-chest: "&7提示: 输入 &6/chestsort&7 来启用自动整理"
message-when-using-chest2: "&7提示: 输入 &6/chestsort&7 来关闭自动整理"
message-sorting-disabled: "&7自动整理已 &c关闭&7."
message-sorting-enabled: "&7自动整理已 &a启用&7."
message-player-inventory-sorted: "&7已成功整理你的背包"
message-error-players-only: "&c错误: 指令只能由玩家运行"
message-error-invalid-options: "&c错误: 位置选项 %s. 有效选项为 %s"
message-gui-enabled: "&a已启用"
message-gui-disabled: "&c已禁用"
message-gui-middle-click: "鼠标中键"
message-gui-shift-click: "Shift + 单击"
message-gui-double-click: "双击"
message-gui-shift-right-click: "Shift + 双击"

**Comment by mfnalex** [comment]
Thanks, I will add this to the next release.
