### ISSUE TITLE
How to add permissions to use /chestsort

### ISSUE THREAD

**Issue by DavidProf** [JEFF-Media-GbR/Spigot-ChestSort#47]
**How to add permissions to use /chestsort**
I'm always frustrated when try to add permissions to use "chestsort.inventory", maybe this is a noob question. But where I should put this and how?

I have no idea how to look to activate this
```
chestsort.use
Allows usage of automatic chest sorting and the /chestsort command.

chestsort.use.inventory
Allows usage of the /invsort command to sort the player's inventory
```
I already look in so many blogs, but I can't do this for myself, I'd like to see some example and file location if was the case. Something like: Put this "example here" in file "example file". Or something like: Type this command in server prompt.

Really sorry, I just don't know where to ask more, I'm like a noob in minecraft server...

**Comment by mfnalex** [comment]
You need a permissions plugin. Sorry, but this really is not ChestSort related. Have a look at this: https://www.spigotmc.org/resources/1-8-1-14-lightperms.62447/

**Comment by DavidProf** [comment]
> You need a permissions plugin. Sorry, but this really is not ChestSort related. Have a look at this: https://www.spigotmc.org/resources/1-8-1-14-lightperms.62447/

Sorry and thanks...

**Comment by mfnalex** [comment]
No problem! If you have any questions, just message me at mail at jeff-media.de
