### ISSUE TITLE
Gesture operation for quickly placing items

### ISSUE THREAD

**Issue by BackWheel** [JEFF-Media-GbR/Spigot-ChestSort#49]
**Is your feature request related to a problem? Please describe.**
I want to make this plugin support gesture operations

**Describe the solution you'd like**
For example, when I open chest and press the space bar + right click, I can take out all the items in the chest, or I can also press the space bar + left click to inventory me Put all the items in the box. In addition, when I open the chest, I can click the part outside the GUI range of the chest to quickly close the chest

**Describe alternatives you've considered**
No

**Additional context**
No

**Comment by mfnalex** [comment]
Pressing the space button is not sent from the client to the server so there is no way to detect that.

**Comment by BackWheel** [comment]
I just give an example, maybe this operation can be achieved through other key combinations?

**Comment by mfnalex** [comment]
Yes, I will leave this issue open as a reminder and might come back to this later.

**Comment by mfnalex** [comment]
I just wanted to implement the following:

1. Shift+Left-Click outside of chest will put your inventory into the chest
2. Shift+Right-Click outside of chest will put everything from the chest into your inventory

However, there is a problem: it is not possible to detect a Shift-Click outside of the inventory.
event.isShiftClick() always returns false when clicking outside of the inventory.

The only alternative I can think of is using ONLY left-click or right-click. :/

**Comment by mfnalex** [comment]
Preview version including the two new hotkeys: https://github.com/JEFF-Media-GbR/Spigot-ChestSort/releases/tag/8.0-pre1

**Comment by mfnalex** [comment]
Added in version 8.0
