### ISSUE TITLE
API - Strict Slots

### ISSUE THREAD

**Issue by SnackMix** [JEFF-Media-GbR/Spigot-ChestSort#5]
Would it be possible to add a boolean for strict slot sorting?
`chestSort.sortInventory(Inventory inventory, int startSlot, int endSlot, boolean strict);`

What I mean is if I used the below code to only sort the top part of a players inventory.
`chestSort.sortInventory(inventory, 9, 35);`
It stores the items in the first empty slot starting from 0.
I would like it to be `strict` so it stores items starting from `startSlot`.

Thanks for the awesome plugin, a real timesaver 😄

**Comment by mfnalex** [comment]
Do you have an idea on how to implement this? Because my only idea was to use placeholder items, but that did not work as expected.
Also, manually combining ItemStacks is not an option because it might break stuff with custom tags.

**Comment by Combustible** [comment]
Agreed, this would be awesome. Doesn't seem reasonable to use this to sort the player's inventory (excluding hotbar/armor) without this feature.

**Comment by SnackMix** [comment]
Not sure the mechanics behind the plugin, but quickly looking at it, would this not work?

Switch `addItem` on this line https://github.com/JEFF-Media-GbR/Spigot-ChestSort/blob/master/src/de/jeffclan/JeffChestSort/JeffChestSortOrganizer.java#L256 to use `setItem(int index, ItemStack item)` instead of `addItem` which tries to fill empty slots in the inventory.

**Comment by mfnalex** [comment]
That leads to problems. What if you have one cookie in the first slot, and nothing in the second, and you want to add a cookie to the inventory? It would not be stacked then.

**Comment by SnackMix** [comment]
It would probably be best to create a separate method for this so it doesn't cause problems with other plugin users.

**Comment by mfnalex** [comment]
If anyone has an idea for implementing this, that would be nice.

**Comment by SnackMix** [comment]
I'll fork this and see what I can come up with to possibly help.

**Comment by mfnalex** [comment]
Thanks, it would be awesome if someone finds a reasonable solution

**Comment by mfnalex** [comment]
Fixed
