### ISSUE TITLE
Updata the Chinese (Traditional) 繁體中文

### ISSUE THREAD

**Issue by Command1264** [JEFF-Media-GbR/Spigot-ChestSort#55]
**Is your feature request related to a problem? Please describe.**
Updata the Chinese (Traditional) 繁體中文

**Describe the solution you'd like**
message-when-using-chest: "&7小提醒: 輸入 &6/chestsort&7 來開啟自動整理箱子"
message-when-using-chest2: "&7小提醒: 輸入 &6/chestsort&7 來關閉自動整理箱子"
message-sorting-disabled: "&7自動整理箱子已 &c關閉&7"
message-sorting-enabled: "&7自動整理箱子已 &a開啟&7"
message-inv-sorting-disabled: "&7自動整理背包已 &c關閉&7."
message-inv-sorting-enabled: "&7自動整理背包已 &a開啟&7."
message-player-inventory-sorted: "&7你的背包已成功整理."
message-error-players-only: "&c錯誤: 這個指令只能由玩家使用"
message-error-invalid-options: "&c錯誤: 未知選項 %s. 有效的選項為 %s."
message-gui-enabled: "&a開啟"
message-gui-disabled: "&c關閉"
message-gui-middle-click: "中鍵"
message-gui-shift-click: "Shift + 左鍵"
message-gui-double-click: "雙擊左鍵"
message-gui-shift-right-click: "Shift + 右鍵"

**Describe alternatives you've considered**

**Additional context**

**Comment by mfnalex** [comment]
Thank you! WIll be added with the next update!
