### ISSUE TITLE
Custom GUI Issue

### ISSUE THREAD

**Issue by Makkief** [JEFF-Media-GbR/Spigot-ChestSort#57]
I can sort custom GUIs and take Items from there when using hotkeys.
Is it possible to detect custom GUIs?

**Comment by mfnalex** [comment]
That depends on which plugin's GUI you are using. Can you please tell me the plugins?

**Comment by Makkief** [comment]
Dynamic Shop... etc
Hmm... isn't possible to check if inventory is just normal chest placed on ground?

**Comment by mfnalex** [comment]
I will have a look, thank you for the report

**Comment by mfnalex** [comment]
This does only happen for the two new shortcuts (left-/right-click outside inventory), right?

**Comment by Makkief** [comment]
No all of hotkeys I think

**Comment by mfnalex** [comment]
> No all the hotkeys work on custom GUI

Well I just tried it with Dynamic Shop ( https://www.spigotmc.org/resources/ss-dynamic-shop-1-13-1-15-2.65603/ ) and it only worked with the new hotkeys.
I will have a look again

**Comment by mfnalex** [comment]
Please try again using the latest 8.3 version

**Comment by Makkief** [comment]
I guess the new feature works fine thanks
I will let you know if there is a problem.

**Comment by Makkief** [comment]
Have you tested Inventory Pages recently?

**Comment by Makkief** [comment]
##### InventoryPages #####
# When InventoryPages is installed, ChestSort will not sort
# the "Next Page" and "Prev Page" buttons. You should not
# disable this behaviour unless you know what you are doing!
hook-inventorypages: true

I set this true but It takes InventoryPages button from my inventory.

**Comment by mfnalex** [comment]
Thanks, I will fix this

**Comment by mfnalex** [comment]
Fixed in c17fd9dc5a2e6bc34d8bae217a89aa583f468e2f

**Comment by mfnalex** [comment]
Please check and tell me if it now works as expected :) Sorry for the trouble, I totally forgot that I wrote an extra hook for InventoryPages.

Most 3rd party plugins should not cause any problems, but if they do, please open a new issue :)

**Comment by Makkief** [comment]
not fixed yet

**Comment by Makkief** [comment]
items:
  # The previous page button item
  prev:
    id: PAPER
    position: 18
    name: '&f이전'
    lore:
      - '&f{CURRENT}/{MAX}'
    modeldata: 11

  # The next page button item
  next:
    id: PAPER
    position: 26
    name: '&f다음'
    lore:
      - '&f{CURRENT}/{MAX}'
    modeldata: 9

  # The no page button item
  noPage:
    id: PAPER
    name: '&f첫 인벤토리'
    lore:
      - '&f{CURRENT}/{MAX}'
    modeldata: 11

**Comment by Makkief** [comment]
items:
  prev:
    id: PAPER
    position: 18
    name: '&f이전'
    lore:
      - '&f{CURRENT}/{MAX}'
    modeldata: 11

  next:
    id: PAPER
    position: 26
    name: '&f다음'
    lore:
      - '&f{CURRENT}/{MAX}'
    modeldata: 9

  noPage:
    id: PAPER
    name: '&f첫 인벤토리'
    lore:
      - '&f{CURRENT}/{MAX}'
    modeldata: 11

**Comment by Makkief** [comment]
This is my config.yml for InventoryPages.
I added modeldata.

**Comment by Makkief** [comment]
not fixed yet.
It still takes InventoryPages button from my inventory and put them to the chest.

**Comment by mfnalex** [comment]
Are you using the latest version?

**Comment by mfnalex** [comment]
Fixed in e2e05c0c3fd06a3f381223a5ac13a61079aeef89
