### ISSUE TITLE
updata Chinese (Traditional) 繁體中文 to v.8.4

### ISSUE THREAD

**Issue by Command1264** [JEFF-Media-GbR/Spigot-ChestSort#58]
**Is your feature request related to a problem? Please describe.**
updata Chinese (Traditional) 繁體中文 to v.8.4

**Describe the solution you'd like**
message-when-using-chest: "&7小提醒: 輸入 &6/chestsort&7 來開啟自動整理箱子"
message-when-using-chest2: "&7小提醒: 輸入 &6/chestsort&7 來關閉自動整理箱子"
message-sorting-disabled: "&7自動整理箱子已 &c關閉&7"
message-sorting-enabled: "&7自動整理箱子已 &a開啟&7"
message-inv-sorting-disabled: "&7自動整理背包已 &c關閉&7."
message-inv-sorting-enabled: "&7自動整理背包已 &a開啟&7."
message-player-inventory-sorted: "&7你的背包已成功整理."
message-error-players-only: "&c錯誤: 這個指令只能由玩家使用"
message-error-invalid-options: "&c錯誤: 未知選項 %s. 有效的選項為 %s."
message-gui-enabled: "&a開啟"
message-gui-disabled: "&c關閉"
message-gui-middle-click: "中鍵"
message-gui-shift-click: "Shift + 左鍵"
message-gui-double-click: "雙擊左鍵"
message-gui-shift-right-click: "Shift + 右鍵"
message-gui-left-click: "填滿箱子 (左鍵)"
message-gui-right-click: "清空箱子 (右鍵)"

**Describe alternatives you've considered**

**Additional context**

**Comment by mfnalex** [comment]
Thank you :) will be added in the next update

**Comment by BackWheel** [comment]
```
message-when-using-chest: "&7提示: 输入 &6/chestsort&7 来启用自动整理箱子."
message-when-using-chest2: "&7提示: 输入 &6/chestsort&7 来关闭自动整理箱子."
message-sorting-disabled: "&7自动整理箱子已 &c关闭&7."
message-sorting-enabled: "&7自动整理箱子已 &a启用&7."
message-inv-sorting-disabled: "&7自动整理背包已 &c关闭&7."
message-inv-sorting-enabled: "&7自动整理背包已 &a开启&7."
message-player-inventory-sorted: "&7已成功整理你的背包."
message-error-players-only: "&c错误: 指令只能由玩家运行."
message-error-invalid-options: "&c错误: 位置选项 %s. 有效选项为 %s."
message-gui-enabled: "&a开启"
message-gui-disabled: "&c关闭"
message-gui-middle-click: "中键"
message-gui-shift-click: "Shift + 左键"
message-gui-double-click: "双击左键"
message-gui-shift-right-click: "Shift + 右键"
message-gui-left-click: "填充箱子 (左键)"
message-gui-right-click: "清空箱子 (右键)"
```

Let me add the translation of Simplified Chinese！

**Comment by mfnalex** [comment]
Thx :)
