### ISSUE TITLE
problem about the ineffective translation

### ISSUE THREAD

**Issue by BackWheel** [JEFF-Media-GbR/Spigot-ChestSort#59]
**Used ChestSort version**
8.4

**Used Spigot version**
Paper(304) 1.15.2-R0.1-SNAPSHOT

**Describe the bug**
I tried to translate the language part in config to Chinese, but it still shows English in the game

**To Reproduce**
1. Modify your language in config
2.Reload server
3.Join the game, use chestsort related commands

**Expected behavior**
It should display information related to Chinese.

**Additional context**
No

**Comment by mfnalex** [comment]
Please post your complete config file. Also did you only reload or properly restart the server?

**Comment by mfnalex** [comment]
Reloading will not work. You need to restart the server.

**Comment by BackWheel** [comment]
I try

**Comment by BackWheel** [comment]
OK, I tried to restart the server completely, but all the prompts became garbled

**Comment by BackWheel** [comment]
![image](https://user-images.githubusercontent.com/41251296/82563311-6dac2d00-9ba9-11ea-855a-e668acb73ac6.png)

**Comment by Makkief** [comment]
change the format to UTF-8

**Comment by mfnalex** [comment]
Are you using Windows? Please use Notepad++ ( https://notepad-plus-plus.org/ ) to edit your config.yml, and then use Encoding->UTF8 and Encoding->Convert to UTF8.
