### ISSUE TITLE
About the hotkey failure of filling the chest

### ISSUE THREAD

**Issue by BackWheel** [JEFF-Media-GbR/Spigot-ChestSort#60]
**Used ChestSort version**
8.4

**Used Spigot version**
Paper(304) 1.15.2-R0.1-SNAPSHOT

**Describe the bug**
When I move the mouse to click the left button outside the chest interface, I cannot put the items in the inventory into it. I have made sure that I have turned on the hotkey

**To Reproduce**
1.Open hotkey
2.Open chest and use the hotkey
3.Found unusable

**Expected behavior**
It should be able to put all the items in my inventory into the chest

**Additional context**
No

**Comment by mfnalex** [comment]
I will check this tomorrow when I am back at home

**Comment by mfnalex** [comment]
Everything works as it should.

1. Use /chestsort hotkeys and enable the Left-Click hotkey
2. Open a chest
3. Left-Click outside of the inventory
4. All stuff from your inventory except hotbar will be put into the chest.

![](http://api.jeff-media.de/chestsort/github/img/hotkey.gif)

**Comment by mfnalex** [comment]
Did you meanwhile get it to work?

**Comment by BackWheel** [comment]
I seem to have found the reason. Auto-filling chest seems not to put the bottom column of the inventory into the chest. If this is intentional, please close my question XD

**Comment by mfnalex** [comment]
Yes, the hotbar stays untouched.
