### ISSUE TITLE
InventoryPages still not fixed

### ISSUE THREAD

**Issue by Makkief** [JEFF-Media-GbR/Spigot-ChestSort#61]
not fixed yet.
It still takes InventoryPages's buttons from my inventory and put them to the chest.

**Comment by mfnalex** [comment]
Strange, should not happen. I will have a look tomorrow because I am not home until then

**Comment by Makkief** [comment]
I found the reason.

It only occurs when the name of Buttons start with '&f'.

in InventoryPageHook
item.getType() == nextMat && item.getItemMeta().getDisplayName().equals(nextName))

There is a problem with check if item's displayname is same with nextName.

It works fine with &8 but when I use &f, I doesn't work.

**Comment by Makkief** [comment]
It's really strange... I just changed the name of Button to
'&e&fNext Page', and now It works fine.

I think there is no problem with the code above but &f.

**Comment by mfnalex** [comment]
Well thats strange. I will have a look tomorrow and will try to fix it :)

**Comment by mfnalex** [comment]
I can confirm that there is indeed a problem when using &f. I will have a look at it
