### ISSUE TITLE
I've disabled some hotkeys, but they're still working

### ISSUE THREAD

**Issue by blatant-trapdoor** [JEFF-Media-GbR/Spigot-ChestSort#65]
**Used ChestSort version**
8.7

**Used Spigot version**
PaperMC-273

**Describe the bug**
I've disabled every hotkey other than middle-click, yet they're all still working.

**To Reproduce**
Yes, I feel it's described above, and an easily understood problem.

**Expected behavior**
Double click, shift-click, and shift-right-click to not work when disabled.

**Additional context**
I've tried reloading the jar, and the config.

**Comment by mfnalex** [comment]
Every player can individually enable/disable hotkeys using /chestsort hotkeys. In the config, you can only define what hotkeys are available by default for new players.

**Comment by blatant-trapdoor** [comment]
Thank you

**Comment by mfnalex** [comment]
You're welcome
