### ISSUE TITLE
Include the version as part of the jar's filename

### ISSUE THREAD

**Issue by drazisil** [JEFF-Media-GbR/Spigot-ChestSort#70]
**Is your feature request related to a problem? Please describe.**

When downloading a new version it's hard to know what version is which

**Describe the solution you'd like**

I would really like if you could add the version number to the plugin's jar filename.

**Describe alternatives you've considered**

* Searching for and deleting prior versions of the plugin prior to downloading
* Creating a PR to solve this (will still do if approved)

**Additional context**

No other context. Thank you for your hard work, and a great plugin!

**Comment by mfnalex** [comment]
Thank you. I think it is actually handy to NOT include the version because the server admin can simply drop the new jar into the plugin directory without having to delete the old version.

If you want the version in the file name, just download the jar from our maven repo: https://repo.jeff-media.de/maven2/de/jeff_media/ChestSort/

**Comment by mfnalex** [comment]
Btw, do you use the integrated Update Checker? It will tell you when a new version is released :)

**Comment by drazisil** [comment]
Fair point. It's probably a "feature: of the Debian file manager that isn't not prompting me to overwrite, I'll check my settings.

I do indeed use the version checker. It don't download direct to the server though, does it?

I'll use the maven version, thanks!

**Comment by mfnalex** [comment]
No, the update checker will only print a message in the console and to OP‘s chat when a new version is available, it will not download the new file by itself.
