### ISSUE TITLE
Bug in click items

### ISSUE THREAD

**Issue by JavituRec** [JEFF-Media-GbR/Spigot-ChestSort#71]
**Used ChestSort version**
Some users when they disable the order in their chests, what happens is shown in the video.

**Used Spigot version**
1.15.2

**Describe the bug**
https://www.youtube.com/watch?v=EroU2A6iQnI

**Comment by mfnalex** [comment]
They have the double click hotkey enabled. -> /chestsort hotkeys

**Comment by mfnalex** [comment]
Btw you can disable hotkeys being enabled by default for new players in the config.yml

**Comment by JavituRec** [comment]
Yeah, that's what I did in the config. But it hasn't been applied yet, because the plugin has no reload.

**Comment by mfnalex** [comment]
Disabling it in the config will not change anything for players that already joined the server. It only sets if new players have those enabled by default.

See line 94 following in the config: https://github.com/JEFF-Media-GbR/Spigot-ChestSort/blob/master/src/main/resources/config.yml#L94

You can only disable hotkeys globally, or let each user decide on his own what hotkeys he/she wants to have enabled.

**Comment by mfnalex** [comment]
Adding a reload command is on the todo list but it has low priority though.

**Comment by mfnalex** [comment]
/chestsort reload has been added in f8c29130183013e47db02f41fc034cac3051267b
