### ISSUE TITLE
No permissions even after giving permissions.

### ISSUE THREAD

**Issue by xAphex** [JEFF-Media-GbR/Spigot-ChestSort#8]
**Used version**
PaperSpigot: 1.13.2
ChestSort: 3.4

**Describe the bug**
When a player uses /sort or /chestsort it says no permissions even when the player/group has permissions.
Permissions plugin: LuckPerms 4.4.1

**To Reproduce**
Install plugin
restart
add permission `chestsort.use` to group/player
restart
use /sort or /chestsort and it says no permissions

**Expected behavior**
It's expected to work when you execute the command because the player/group has permissions.

**Additional context**
![noperms](https://user-images.githubusercontent.com/5391237/56467526-89825400-6428-11e9-8406-c0f55ca9fd27.png)

**Comment by xAphex** [comment]
Fixed the issue by removing the permission and adding it again.
Sorry for the trouble.

**Comment by mfnalex** [comment]
No problem!
