### ISSUE TITLE
support for "Custom Enderchest"

### ISSUE THREAD

**Issue by AcesGamingUK** [JEFF-Media-GbR/Spigot-ChestSort#80]
> **Is your feature request related to a problem? Please describe.**

Cant seem to get the plugin to work with [Custom EnderChest](https://www.spigotmc.org/resources/custom-enderchest.8868/)

> **Describe the solution you'd like**

Potentially have full implementation

**Comment by mfnalex** [comment]
What doesnt work?

**Comment by AcesGamingUK** [comment]
oh my bad, i can't get ant of the click functions to work

- Middle click (mousewheel) on ANY inventory slot
- Shift + left click on any EMPTY inventory slot
- Double click on any EMPTY inventory slot
- Shift + right click on any EMPTY inventory slot
- Left-Click outside inventory
- Double-Left-Click outside inventory
- Right-Click outside inventory
- Double-Right-Click outside inventory

**Comment by mfnalex** [comment]
Okay, I can fix this, but it requires changes in the Custom Enderchest plugin. I will create a pull request and if the author accepts, I can add support for the next version.

**Comment by mfnalex** [comment]
This is the line that prevents ChestSort from sorting CustomEnderChests: https://github.com/JEFF-Media-GbR/Spigot-ChestSort/blob/master/src/main/java/de/jeff_media/ChestSort/ChestSortListener.java#L337

I will have a look at this the next days to see what I can do. Unfortunately CustomEnderChests doesn't use maven so it's a mess to work on.

**Comment by AcesGamingUK** [comment]
ok thank you for looking, 
it's honestly no big deal, was just something I noticed :)

**Comment by mfnalex** [comment]
I have asked the author to make a small change to his plugin so I can add support easily :)
https://github.com/brunyman/CustomEnderChest/issues/13

**Comment by mfnalex** [comment]
I have added support for ChestSort to CustomEnderChest ( https://github.com/brunyman/CustomEnderChest/pull/14/commits/3066904f9782a9767af48f08bab1c5f84a97c78a ). If the author does not accept my Pull request in time, feel free to join my discord ( https://discord.com/invite/Jckqsa4 ) so I can send you the CustomEnderChest.jar file
