### ISSUE TITLE
Russian Translation

### ISSUE THREAD

**Issue by Saharo4eks** [JEFF-Media-GbR/Spigot-ChestSort#82]
**Language**
Russian (from Gandon)

**Translation**
message-when-using-chest: "&7Подсказка: введите &6/chestsort&7, чтобы включить автоматическую сортировку вещей в сундуках."
message-when-using-chest2: "&7Подсказка: введите &6/chestsort&7, чтобы отключить автоматическую сортировку вещей в сундуках."
message-sorting-disabled: "&7Автоматическая сортировка вещей в сундуках была &cотключена&7."
message-sorting-enabled: "&7Автоматическая сортировка вещей в сундуках была &aвключена&7."
message-inv-sorting-disabled: "&7Автоматическая сортировка вещей в инвентаре &cотключена&7."
message-inv-sorting-enabled: "&7Автоматическая сортировка вещей в инвентаре &aвключена&7."
message-player-inventory-sorted: "&7Ваш инвентарь был отсортирован."
message-error-players-only: "&cОшибка: эта команда может быть использована только игроками."
message-error-invalid-options: "&cОшибка: Неизвестная опция %s. Допустимые опции: %s."
message-gui-enabled: "&aАктивировано"
message-gui-disabled: "&cОтключено"
message-gui-middle-click: "Колесико"
message-gui-shift-click: "Shift + Клик"
message-gui-double-click: "Двойной клик"
message-gui-shift-right-click: "Shift + Правый клик"
message-gui-left-click: "Заполнить сундук (ЛКМ/Двойной ЛКМ)"
message-gui-right-click: "Освободить сундук (ПКМ/Двойной ПКМ)"

**Comment by mfnalex** [comment]
Thank you!
