### ISSUE TITLE
update Chinese Translation

### ISSUE THREAD

**Issue by XXY233** [JEFF-Media-GbR/Spigot-ChestSort#83]
**Language**
Chinese

**Translation**
message-when-using-chest: "&7提示: 输入 &6/chestsort&7 来启用自动整理箱子."
message-when-using-chest2: "&7提示: 输入 &6/chestsort&7 来关闭自动整理箱子."
message-sorting-disabled: "&7自动整理箱子已 &c关闭&7."
message-sorting-enabled: "&7自动整理箱子已 &a启用&7."
message-inv-sorting-disabled: "&7自动整理背包已 &c关闭&7."
message-inv-sorting-enabled: "&7自动整理背包已 &a开启&7."
message-player-inventory-sorted: "&7已成功整理你的背包."
message-error-players-only: "&c错误: 指令只能由玩家运行."
message-error-invalid-options: "&c错误: 位置选项 %s. 有效选项为 %s."
message-gui-enabled: "&a开启"
message-gui-disabled: "&c关闭"
message-gui-middle-click: "中键"
message-gui-shift-click: "Shift + 左键"
message-gui-double-click: "双击左键"
message-gui-shift-right-click: "Shift + 右键"
message-gui-left-click: "填充箱子 (左键/双击左键)"
message-gui-right-click: "清空箱子 (右键/双击右键)"

**Comment by mfnalex** [comment]
Thanks, will be added in the next update
