### ISSUE TITLE
Very, very minor typo. 

### ISSUE THREAD

**Issue by jacket430** [JEFF-Media-GbR/Spigot-ChestSort#85]
**Used ChestSort version**
8.15.0

In the config.yml generated by the mod upon first launch, there is a very very small typo on one of the lines. I'm not trying to be a snob sorry if it sounds like I am haha.

"Additionally to sorting hotkeys, you can quickly unload your inventory into a chest and vice versa using left-click or **_richt_**-click outside of a chest's inventory."

**Comment by mfnalex** [comment]
thanks :) Of course I will not release it as new update, it will be included in the next release :)
