### ISSUE TITLE
Right click hotkey

### ISSUE THREAD

**Issue by AcesGamingUK** [JEFF-Media-GbR/Spigot-ChestSort#86]
**Used ChestSort version**
8.15.0

**Used Spigot version**
git-Paper-68 (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT) `paper spigot`

**Describe the bug**
Right-clicking to pull/put items results in dirt being pulled out/in

**To Reproduce**
have dirt in inv/chest and use click hotkeys

**Expected behavior**
to only pull/push same items

**Additional context**
no rush to fix bug, take it easy :)

**Comment by mfnalex** [comment]
fixed in https://github.com/JEFF-Media-GbR/Spigot-ChestSort/commit/f935964ef6f9e0bb1c17bbfdaa26bf6b9cab50da
