### ISSUE TITLE
Inventory sort other player's inventory (/isort <playerName>)

### ISSUE THREAD

**Issue by xRebellion** [JEFF-Media-GbR/Spigot-ChestSort#91]
**Is your feature request related to a problem? Please describe.**
I'm kind of planning to make a custom item that sorts your inventory. Rather than giving players the permissions for it, I'd like to give them a limited use item that executes the `/isort <player>` command from console.

**Describe the solution you'd like**
Adding `/isort <playerName>`, though it might conflict with `/isort on|off|toggle`, perhaps `/isort player <playerName>`?

**Describe alternatives you've considered**
Apparently the plugin that allows attaching commands to items needs the player to have the permissions for it, or having the command being run from console, both of which are apparently not desirable/possible. I tried to do like `add permission -> isort -> delete permission`, but it doesn't seem to work as I'd expect it to.

**Additional context**
It's probably a rather odd feature, since the use-cases for it are pretty low, but hopefully it isn't too difficult/wasting your time too much c:. Thank you!

**Comment by mfnalex** [comment]
Thank you for the request, I can add that feature though I dont think I will mention it in the commsnds section at spigotmc because almost noone will use it. If I dont reply until tomorrow, please just remind me here again at github and I will add it on the same day :)

**Comment by mfnalex** [comment]
I will just allow console to sort other's inventories, ok?

On the normal invsort command, you can choose between inventory only, hotbar only, or both. Do you also need those options?

**Comment by xRebellion** [comment]
> I will just allow console to sort other's inventories, ok?
> 
> On the normal invsort command, you can choose between inventory only, hotbar only, or both. Do you also need those options?

Having the command only for console would be fine 😄 

Since sorting the hotbar seems unnecessary, I think inventory only would do just fine for it.

**Comment by mfnalex** [comment]
Try this: https://repo.jeff-media.de/maven2/de/jeff_media/ChestSort/8.17.1-SNAPSHOT/ChestSort-8.17.1-20200718.141954-1.jar

If it works, I will upload it so Spigot tomorrow. I don't have to test it right now, but it should work fine :)

```
## 8.17.1-SNAPSHOT
- Added possibility to sort a player's inventory from console using /invsort <player> [toggle|on|off|hotbar|inv|all]
```

**Comment by xRebellion** [comment]
Apparently it doesn't recognize the playername as an option
![image](https://user-images.githubusercontent.com/32483348/87854994-b7ae5680-c93f-11ea-910e-bfee8c25a0fc.png)

**Comment by xRebellion** [comment]
It seems to work splendidly, thank you very much :D

**Comment by mfnalex** [comment]
You're welcome :) I will release it as update tomorrow. I would be happy if you could take a minute to review ChestSort on SpigotMC if you have time :)

**Comment by xRebellion** [comment]
Definitely will do so! :D
