### ISSUE TITLE
Feature: Players can disable ChestSort

### ISSUE THREAD

**Issue by nitu2003** [JEFF-Media-GbR/Spigot-ChestSort#93]
I have my client modded with sorting mod and have conflicts with ChestSort. But it seems that there is only a config to enable or disable automatic sorting. I want to disable all the sorting actions, including Hotkeys like clicking slots or middle click.

Sorry for my poor English. And I DO need this feature.

**Comment by mfnalex** [comment]
This?
```yaml
allow-sorting-hotkeys: true
```
(Line 132)

**Comment by nitu2003** [comment]
> This?
> 
> ```yaml
> allow-sorting-hotkeys: true
> ```
> 
> (Line 132)

Is that option for all players on the server? I need an option for only one player.

**Comment by mfnalex** [comment]
You can disable hotkeys per player using /chestsort hotkeys
