### ISSUE TITLE
GUI Sort Issue

### ISSUE THREAD

**Issue by yukisho** [JEFF-Media-GbR/Spigot-ChestSort#95]
RPGBank is allowing you to sort their GUI inventory causing items to be duplicated within. Have the generic hook enabled but it's still doing it. I let the author of RPGBank know as well of this with ChestSort.

RPGBank
https://www.spigotmc.org/resources/%E2%9C%85must-have%E2%9C%85-rpgbank-store-your-items-exp-and-money-using-villagers-npcs-and-custom-gui.29139/

**Comment by mfnalex** [comment]
thanks for the report. since its a premium plugin, I cannot test it myself. can you please "debug: true" at the bottom of your chestsort config and send me the console output when the duplication bug happens?

**Comment by mfnalex** [comment]
bump @yukisho

**Comment by mfnalex** [comment]
closing this now, no answer for more than 5 month
