### ISSUE TITLE
Disabling chestsort not working

### ISSUE THREAD

**Issue by NyhmsQuest** [JEFF-Media-GbR/Spigot-ChestSort#98]
**Used ChestSort version**
8.17.7

**Used Spigot version**
Tuinity version git-Tuinity-"ed9e0c4" (MC: 1.16.4) (Implementing API version 1.16.4-R0.1-SNAPSHOT)

**Describe the bug**
Disabling chestsort with either /sort or /chestsort gives you the message saying you disabled it but it's still on and still sorts the chests when using the hotkeys.

**To Reproduce**
Try and disable chestsort and use any of the hotkeys to sort a chest.

**Expected behavior**
Expected to disable chestsort when toggled off.

**Additional context**
Nothing

**Comment by mfnalex** [comment]
That's expected behaviour. Using /sort disabled AUTOMATIC chest sorting, but not hotkey sorting. You can disable hotkeys individually using /chestsort hotkeys
